apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcpo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcpo
  template:
    metadata:
      labels:
        app: mcpo
    spec:
      serviceAccountName: cluster-admin-sa
      containers:
        - name: mcpo-container
          image: ghcr.io/open-webui/mcpo:main
          ports:
            - containerPort: 8000
          command: ["mcpo"] # Entrypoint of the container
          args:
            - "--api-key"
            - "top-secret"
            - "--config"
            - "/etc/config/config.json"
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
      volumes:
        - name: config-volume
          configMap:
            name: mcpo-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mcpo-config
data:
  config.json: |
    {
      "mcpServers": {
        "memory": {
          "command": "npx",
          "args": ["-y", "@modelcontextprotocol/server-memory"]
        },
        "time": {
          "command": "uvx",
          "args": ["mcp-server-time", "--local-timezone=America/New_York"]
        },
        "kubernetes": {
          "command": "npx",
          "args": ["mcp-server-kubernetes"]
        }
    }