apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcpo-deployment
  namespace: suseai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcpo
  template:
    metadata:
      labels:
        app: mcpo
    spec:
      serviceAccountName: cluster-admin-sa
      containers:
        - name: mcpo-container
          image: ghcr.io/open-webui/mcpo:latest
          ports:
            - containerPort: 8000
          command: ["mcpo"] # Entrypoint of the container
          args: 
            - "--api-key"
            - "top-secret"
            - "--config"
            - "/etc/config/config.json"
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
      volumes:
        - name: config-volume
          configMap:
            name: mcpo-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mcpo-config
  namespace: suseai
data:
  config.json: |
    {
      "mcpServers": {
        "kubernetes": {
          "command": "npx",
          "args": [
            "-y",
            "kubernetes-mcp-server@latest"
          ]
        }
      }
    }