apiVersion: v1
kind: Service
metadata:
  name: mcpo-service
spec:
  selector:
    app: mcpo
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000
  type: NodePort # Or ClusterIP if you don't need external access