global:
  imagePullSecrets:
  - application-collection
image:
  # registry: dp.apps.rancher.io
  # repository: containers/open-webui
  # tag: 0.5.14

  registry: ghcr.io
  repository: open-webui/open-webui
  tag: main

  # registry: ghcr.io
  # repository: open-webui/open-webui
  # tag: main
  # repository: ghcr.io/open-webui/open-webui
  # tag: 0.5.10
  pullPolicy: IfNotPresent
ollamaUrls:
- http://suseai-nv-ollama.suseai.svc.cluster.local:11434
persistence:
  storageClass: local-path
ollama:
  enabled: false
pipelines:
  enabled: false
  persistence:
    enabled: false
    storageClass: local-path
tika:
  enabled: True
ingress:
  enabled: true
  class: ""
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  host: ollama
  tls: true
service:
  type: NodePort
  annotations: {}
  port: 80
  containerPort: 8080
  nodePort: 31000
  labels: {}
  loadBalancerClass: ""
# -- OpenAI base API URL to use. Defaults to the Pipelines service endpoint when Pipelines are enabled, and "https://api.openai.com/v1" if Pipelines are not enabled and this value is blank
openaiBaseApiUrl: ""
# -- Env vars added to the Open WebUI deployment. Most up-to-date environment variables can be found here: https://docs.openwebui.com/getting-started/env-configuration/
extraEnvVars:
  # -- Default API key value for Pipelines. Should be updated in a production deployment, or be changed to the required API key if not using Pipelines
- name: OPENAI_API_KEY
  value: "0p3n-w3bu!"
- name: DEFAULT_MODELS
  value: ""
- name: DEFAULT_USER_ROLE
  value: "user"
- name: WEBUI_NAME
  value: "SUSE AI"
- name: GLOBAL_LOG_LEVEL
  value: INFO
- name: RAG_EMBEDDING_MODEL
  value: "sentence-transformers/all-MiniLM-L6-v2"
- name: VECTOR_DB
  value: "milvus"
- name: MILVUS_URI
  value: http://suseai-nv-milvus.suseai.svc.cluster.local:19530
