global:
  imagePullSecrets:
  - application-collection

specs:
  image:
    repository: ollama/ollama
    tag: 0.6.5
    pullPolicy: IfNotPresent
  models:
    pull:
      - "qwen2.5:1.5b"
      - "granite3.3:2b"
    run:
      - "qwen2.5:1.5b"
      - "granite3.3:2b"
ingress:
  enabled: false
service:
  type: ClusterIP
  annotations: {}
  port: 80
  containerPort: 8080
  labels: {}
  loadBalancerClass: ""
persistentVolume:
  storageClass: local-path