global:
  imagePullSecrets:
  - application-collection

specs:
  image:
    registry: dp.apps.rancher.io
    repository: containers/ollama
    tag: 0.6.2
    pullPolicy: IfNotPresent
    lifecycle:
      postStart:
        exec:
          command:
            - /bin/sh
            - -c
            - |
                for i in $(seq 10); do
                  ollama ps && break
                  sleep 1
                done
                for model in qwen2.5:1.5b; do
                  ollama pull "$model"
                done
ingress:
  enabled: false
service:
  type: NodePort
  nodePort: 31434
persistentVolume:
  storageClass: local-path