global:
  imagePullSecrets:
  - application-collection

specs:
  image:
    registry: dp.apps.rancher.io
    repository: containers/ollama
    tag: 0.6.2
    pullPolicy: IfNotPresent

ingress:
  enabled: false
service:
  type: NodePort
  nodePort: 31434
persistentVolume:
  storageClass: local-path

ollama: 
  # -- List of models to pull at container startup
  models:
    pull:
      - qwen2.5:1.5b
