global:
  imagePullSecrets:
  - application-collection

specs:
  image:
    registry: dp.apps.rancher.io
    repository: containers/ollama
    tag: 0.6.2
    pullPolicy: IfNotPresent
  models:
    pull:
      - "qwen2.5:1.5b"
      - "granite3.3:2b"
    run:
      - "qwen2.5:1.5b"
      - "granite3.3:2b"
ingress:
  enabled: false
service:
  type: NodePort
  annotations: {}
  port: 80
  containerPort: 8080
  nodePort: 32434
  labels: {}
  loadBalancerClass: ""
persistentVolume:
  storageClass: local-path